export const Equal = Symbol('=')
export const NotEqual = Symbol('!=')
export const Or = Symbol('OR')
export const LT = Symbol('<')
export const GT = Symbol('>')
export const LTE = Symbol('<=')
export const GTE = Symbol('>=')
export const Between = Symbol('BETWEEN... AND...')
export const NotBetween = Symbol('NOT BETWEEN... AND...')
export const In = Symbol('IN (...)')
export const NotIn = Symbol('NOT IN (...)')
export const Like = Symbol('LIKE')
export const NotLike = Symbol('NOT LIKE')
export const Null = Symbol('IS NULL')
export const NotNull = Symbol('IS NOT NULL')
export const RegExp = Symbol('REGEXP')
export const NotRegExp = Symbol('NOT REGEXP')
export const Not = Symbol('NOT')
export const Exists = Symbol('EXISTS(...)')
export const NotExists = Symbol('NOT EXISTS(...)')
export const Any = Symbol('ANY')
export const All = Symbol('ALL')